### ISSUE TITLE
CR-812 & 813 Approval WF and Voucher Posting

### ISSUE THREAD

**Issue by 0340LalitGupta** [Isgec/WebSpmt1#17]
1. Approval WF in supplier payment portal
2. Auto Voucher Posting

**Comment by 0340LalitGupta** [comment]
Workflow part is under implementation.
Case logged in INFOR for PGN voucher posting.

**Comment by 0340LalitGupta** [comment]
Auto Voucher Posting [PGN] can not be done, confirmed by INFOR.
Workflow part is checked by Pawan and is Okay.
Rollout is hold by Accounts.
@hariharan-isgec 
Can it be closed.

**Comment by hariharan-isgec** [comment]
Closed as technically not possible
